{% set name = "kinisi" %}
{% set version = "2.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kinisi-{{ version }}.tar.gz
  sha256: d02f75a7a1777fdcf4cd00d907aa3441c8232d8dde22606f00dbb39864d601fd
  patches:
    - bs4.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - bs4 >=0.0.2
    - dynesty >=2.1.5
    - emcee >=3.1.6
    - scipp >=24.8.0
    - uncertainties >=3.2.3
    - python >={{ python_min }}
    - numpy >=2.0.0
    - scikit-learn >=1.5.0
    - scipy >=1.9.3
    - tqdm
    - uravu >=1.3.0
    - statsmodels >=0.14.0
    - beautifulsoup4

test:
  imports:
    - kinisi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bjmorgan/kinisi
  summary: Efficient estimation of diffusion processes from molecular dynamics.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
